In [1]:
#Import dependencies

import pandas as pd

In [2]:
#Designate URL

url = 'https://en.wikipedia.org/wiki/List_of_languages_by_time_of_extinction'

In [87]:
#Read tables from URL using pandas

tables = pd.read_html(url)

In [48]:
#Turn each table into a dataframe by index

twentyfirst_df = tables[1]
twentieth_df = tables[2]
nineteenth_df = tables[3]
eighteenth_df = tables[4]
seventeenth_df = tables[5]
sixteenth_df = tables[6]
fifteenth_df = tables[7]
fourteenth_df = tables[8]
thirteenth_df = tables[9]
eleven_twelve_df = tables[10]
tenth_df = tables[11]
ninth_df = tables[12]
seventh_df = tables[13]
sixth_df = tables[14]
fifth_df = tables[15]
fourth_df = tables[16]
third_df = tables[17]
second_df = tables[18]
first_df = tables[19]
first_BCE_df = tables[20]
second_BCE_df = tables[21]
third_BCE_df = tables[22]
fourth_BCE_df = tables[23]
fifth_BCE_df = tables[24]
sixth_BCE_df = tables[25]
seventh_BCE_df = tables[26]
second_mil_BCE_df = tables[27]

In [61]:
#Create new column designating the century of death for timeline charts 
#identify dates for each century

twentyfirst_df['Century of Death'] = '2001-2100'
twentieth_df['Century of Death']= '1901-2000'
nineteenth_df['Century of Death']= '1801-1900'
eighteenth_df['Century of Death'] = '1701-1800'
seventeenth_df['Century of Death'] = '1601-1700'
sixteenth_df['Century of Death'] = '1501-1600'
fifteenth_df['Century of Death'] = '1401-1500'
fourteenth_df['Century of Death'] = '1301 - 1400'
thirteenth_df['Century of Death'] = '1201-1300'
eleven_twelve_df['Century of Death'] = '1001-1200'
tenth_df['Century of Death'] = '901-1000'
ninth_df['Century of Death'] = '801-900'
seventh_df['Century of Death'] = '601-700'
sixth_df['Century of Death'] = '501-600'
fifth_df['Century of Death'] = '401-500'
fourth_df['Century of Death'] = '301-400'
third_df['Century of Death'] = '201-300'
second_df['Century of Death'] = '101-200'
first_df['Century of Death'] = '1-100'
first_BCE_df['Century of Death'] = '100-1 BCE'
second_BCE_df['Century of Death'] = '200-101 BCE'
third_BCE_df['Century of Death'] = '300-201 BCE'
fourth_BCE_df['Century of Death'] = '400-301 BCE'
fifth_BCE_df['Century of Death'] = '500-401 BCE'
sixth_BCE_df['Century of Death'] = '600-501 BCE'
seventh_BCE_df['Century of Death'] = '700-601 BCE'
second_mil_BCE_df['Century of Death'] = '2000-1001 BCE'

In [88]:
#Put all dataframes into a variable that we can concatinate into one large dataframe

all_frames = [twentyfirst_df, twentieth_df, nineteenth_df, eighteenth_df, seventeenth_df,
              sixteenth_df, fifteenth_df, fourteenth_df, thirteenth_df, eleven_twelve_df,
              tenth_df, ninth_df, seventh_df, sixth_df, fifth_df, fourth_df, third_df,
              second_df, first_df, first_BCE_df, second_BCE_df, third_BCE_df, fourth_BCE_df,
              fifth_BCE_df, sixth_BCE_df, seventh_BCE_df, second_mil_BCE_df]

#Concatinate all frames into one big dataframe

final_frames = pd.concat(all_frames)

In [90]:
#Delete the column names from the consolidated datframethat were indexed as a row of data
#update column headers

final_frames.drop([0,0],axis=0).rename(columns = {0: 'Date',
                                                 1: 'Language',
                                                 2: 'Language Family',
                                                 3: 'Region',
                                                 4: 'Notes'})

,Date,Language,Language Family,Region,Notes,Century of Death
1,9 December 2016,Mandan,Siouan,"North Dakota, United States",with the death of Edwin Benson[1],2001-2100
2,30 August 2016,Wichita,Caddoan,"Oklahoma, United States",with the death of Doris McLemore[2],2001-2100
3,29 July 2016,Gugu Thaypan,Pama-Nyungan,"Queensland, Australia",with the death of Tommy George[3],2001-2100
4,February 2016,Nuchatlaht dialect of Nuu-chah-nulth,Wakashan,"British Columbia, Canada",with the death of Alban Michael[4],2001-2100
5,by 2016,Amurdag,Iwaidjan,"Northern Territory, Australia",with the death of Charlie Mungulda[5],2001-2100
6,4 February 2014,Klallam,Salishan,"Washington, United States",with the death of Hazel Sampson[6],2001-2100
7,5 June 2013,Livonian,Uralic > Finnic,Latvia,with the death of Grizelda Kristina[7],2001-2100
8,26 March 2013,Yurok,Algic,"California, United States",with the death of Archie Thompson[8],2001-2100
9,2 October 2012,Cromarty dialect of Scots,Germanic,"Northern Scotland, United Kingdom",with the death of Bobby Hogg [9],2001-2100
10,ca. 2012,Dhungaloo,Pama-Nyungan,"Queensland, Australia",with the death of Roy Hatfield[10],2001-2100
11,11 July 2012,Upper Chinook,Chinookan,"Oregon, United States",with the death of Gladys Thompson[11],2001-2100
12,10 March 2012,Holikachuk,Na-Dene,"Alaska, United States","with the death of Wilson ""Tiny"" Deacon[12]",2001-2100
13,2011,Lower Arrernte,Pama-Nyungan,"Northern Territory, Australia",with the death of Brownie Doolan Perrurle[13],2001-2100
14,24 October 2010,Pazeh,Austronesian,Taiwan,with the death of Pan Jin-yu[14],2001-2100
15,20 August 2010,Cochin Indo-Portuguese Creole,Portuguese-based Creole,Southern India,with the death of William Rozario[14],2001-2100
16,26 January 2010,Aka-Bo,Andamanese,"Andaman Islands, India",with the death of Boa Sr.[15],2001-2100
17,November 2009,Aka-Kora,Andamanese,"Andaman Islands, India",with the death of Ms. Boro[16],2001-2100
18,2009,Aka-Jeru,Andamanese,"Andaman Islands, India",[17],2001-2100
19,2009,Nyawaygi,Pama-Nyungan,"Queensland, Australia",with the death of Willie Seaton[18],2001-2100
20,by 2009,Gugu Badhun,Pama-Nyungan,"Queensland, Australia",NaN,2001-2100
21,by 2009,Muruwari,Pama-Nyungan,"Queensland and New South Wales, Australia",[19],2001-2100
22,by 2009,Agavotaguerra,Arawakan,Brazil,[20],2001-2100
23,by 2009,Arikem,Tupian,Brazil,[21],2001-2100
24,by 2009,Karipúna,Tupian,Brazil,[22],2001-2100
25,by 2009 [23],Pataxó Hã-Ha-Hãe,unclassified,Brazil,NaN,2001-2100
26,by 2009,Aribwatsa,Malayo-Polynesian,Papua New Guinea,[24],2001-2100
27,by 2009,Lelak,Malayo-Polynesian,"Sarawak, Malaysia",[4],2001-2100
28,by 2009,Papora-Hoanya,Austronesian,Taiwan,[25],2001-2100
29,2008,Plains Apache,Na-Dene > Athabaskan,"Oklahoma, United States",with the death of Alfred Chalepah Jr.,2001-2100
30,after April 2008,Dura,Sino-Tibetan,Nepal,with the death of Soma Devi Dura[26],2001-2100
...,...,...,...,...,...,...
1,100 BCE,Vestinian,Italic,east-central Italy,NaN,200-101 BCE
2,ca. 150 BCE,Faliscan,Italic,"Tuscany/Latium, Italy",NaN,200-101 BCE
1,ca. 3rd century BCE,Volscian,Italic,Italy; Latium,NaN,300-201 BCE
2,ca. 3rd century BCE,Aequian,Italic,"Latium, east-central Italy",NaN,300-201 BCE
3,ca. 3rd century BCE,Sidetic,Anatolian,southwestern Anatolia,NaN,300-201 BCE
4,3rd century BCE,Carian,Anatolian,southwestern Anatolia,NaN,300-201 BCE
1,ca. 300 BCE,Philistine,"unclassified, maybe Indo-European",Palestine; Lebanon,NaN,400-301 BCE
2,ca. 300 BCE,Scythian,Iranian,"Pontic-Caspian steppe, Central Asia",evolved into Sarmatian,400-301 BCE
3,4th century BCE,Ancient Macedonian,Indo-European,northeastern Greece,NaN,400-301 BCE
4,ca. 350 BCE,Elamite,isolate,Persia; southern Mesopotamia,NaN,400-301 BCE
5,early 4th century BCE,Eteocypriot,isolate/unclassified,Cyprus,NaN,400-301 BCE
1,ca. 400 BCE,Lepontic,Celtic,northern Italy,NaN,500-401 BCE
2,after 5th century BCE,Tartessian,unclassified,Spain,NaN,500-401 BCE
3,5th century BCE,Ammonite,Semitic,northwestern Jordan,NaN,500-401 BCE
4,5th century BCE,Moabite,Semitic,northwestern Jordan,NaN,500-401 BCE
5,maybe 5th century BCE,Phoenician,Semitic,Lebanon; Palestine; Mediterranean coast,evolved into Punic,500-401 BCE
1,after 6th century BCE,Lemnian,Tyrsenian,"Lemnos, Greece",[208],600-501 BCE
2,6th century BCE,Edomite,Semitic,southwestern Jordan,NaN,600-501 BCE
1,ca. 600 BCE,Luwian,Anatolian,Anatolia; northern Syria,NaN,700-601 BCE
2,ca. 600 BCE,Egyptian,Afroasiatic,Ancient Egypt,evolved into Demotic by 600 BCE,700-601 BCE
3,7th century BCE,Urartian,Hurro-Urartian,Armenia; Georgia; Iraq; Anatolia,NaN,700-601 BCE
4,early 1st millennium BCE,Eteocretan,isolate/unclassified,"Crete, Greece",NaN,700-601 BCE
1,ca. 1550-1050 BCE,Cypro-Minoan,unclassified,Cyprus,NaN,2000-1001 BCE
2,ca. 1100 BCE,Hittite,Anatolian,Anatolia,NaN,2000-1001 BCE
3,after 1170 BCE,Ugaritic,Semitic,Syria,following the destruction of Ugarit,2000-1001 BCE
4,ca. 1200 BCE,Hurrian,Hurro-Urartian,Anatolia; Syria; Mesopotamia,NaN,2000-1001 BCE
5,ca. 1300 BCE,Palaic,Anatolian,northwest Anatolia,NaN,2000-1001 BCE
6,ca. 1500 BCE,Hattic,isolate,Anatolia,NaN,2000-1001 BCE
7,2nd millennium BCE,Eblaite,Semitic,Syria,NaN,2000-1001 BCE
8,early 2nd millennium BCE,Sumerian,isolate,Mesopotamia,used as a literary and liturgical language unt...,2000-1001 BCE